export const BOARD_OF_DIRECTOR_LIST_REQUEST = 'BOARD_OF_DIRECTOR_LIST_REQUEST'
export const BOARD_OF_DIRECTOR_LIST_SUCCESS = 'BOARD_OF_DIRECTOR_LIST_SUCCESS'
export const BOARD_OF_DIRECTOR_LIST_FAIL = 'BOARD_OF_DIRECTOR_LIST_FAIL'

export const BOARD_OF_DIRECTOR_DETAILS_REQUEST = 'BOARD_OF_DIRECTOR_DETAILS_REQUEST'
export const BOARD_OF_DIRECTOR_DETAILS_SUCCESS = 'BOARD_OF_DIRECTOR_DETAILS_SUCCESS'
export const BOARD_OF_DIRECTOR_DETAILS_FAIL = 'BOARD_OF_DIRECTOR_DETAILS_FAIL'

export const BOARD_OF_DIRECTOR_DELETE_REQUEST = 'BOARD_OF_DIRECTOR_DELETE_REQUEST'
export const BOARD_OF_DIRECTOR_DELETE_SUCCESS = 'BOARD_OF_DIRECTOR_DELETE_SUCCESS'
export const BOARD_OF_DIRECTOR_DELETE_FAIL = 'BOARD_OF_DIRECTOR_DELETE_FAIL'

export const BOARD_OF_DIRECTOR_CREATE_REQUEST = 'BOARD_OF_DIRECTOR_CREATE_REQUEST'
export const BOARD_OF_DIRECTOR_CREATE_SUCCESS = 'BOARD_OF_DIRECTOR_CREATE_SUCCESS'
export const BOARD_OF_DIRECTOR_CREATE_FAIL = 'BOARD_OF_DIRECTOR_CREATE_FAIL'
export const BOARD_OF_DIRECTOR_CREATE_RESET = 'BOARD_OF_DIRECTOR_CREATE_RESET'

export const BOARD_OF_DIRECTOR_UPDATE_REQUEST = 'BOARD_OF_DIRECTOR_UPDATE_REQUEST'
export const BOARD_OF_DIRECTOR_UPDATE_SUCCESS = 'BOARD_OF_DIRECTOR_UPDATE_SUCCESS'
export const BOARD_OF_DIRECTOR_UPDATE_FAIL = 'BOARD_OF_DIRECTOR_UPDATE_FAIL'
export const BOARD_OF_DIRECTOR_UPDATE_RESET = 'BOARD_OF_DIRECTOR_UPDATE_RESET'
