export const CONTACT_INFO_LIST_REQUEST = 'CONTACT_INFO_LIST_REQUEST'
export const CONTACT_INFO_LIST_SUCCESS = 'CONTACT_INFO_LIST_SUCCESS'
export const CONTACT_INFO_LIST_FAIL = 'CONTACT_INFO_LIST_FAIL'

export const CONTACT_INFO_DETAILS_REQUEST = 'CONTACT_INFO_DETAILS_REQUEST'
export const CONTACT_INFO_DETAILS_SUCCESS = 'CONTACT_INFO_DETAILS_SUCCESS'
export const CONTACT_INFO_DETAILS_FAIL = 'CONTACT_INFO_DETAILS_FAIL'

export const CONTACT_INFO_DELETE_REQUEST = 'CONTACT_INFO_DELETE_REQUEST'
export const CONTACT_INFO_DELETE_SUCCESS = 'CONTACT_INFO_DELETE_SUCCESS'
export const CONTACT_INFO_DELETE_FAIL = 'CONTACT_INFO_DELETE_FAIL'

export const CONTACT_INFO_CREATE_REQUEST = 'CONTACT_INFO_CREATE_REQUEST'
export const CONTACT_INFO_CREATE_SUCCESS = 'CONTACT_INFO_CREATE_SUCCESS'
export const CONTACT_INFO_CREATE_FAIL = 'CONTACT_INFO_CREATE_FAIL'
export const CONTACT_INFO_CREATE_RESET = 'CONTACT_INFO_CREATE_RESET'

export const CONTACT_INFO_UPDATE_REQUEST = 'CONTACT_INFO_UPDATE_REQUEST'
export const CONTACT_INFO_UPDATE_SUCCESS = 'CONTACT_INFO_UPDATE_SUCCESS'
export const CONTACT_INFO_UPDATE_FAIL = 'CONTACT_INFO_UPDATE_FAIL'
export const CONTACT_INFO_UPDATE_RESET = 'CONTACT_INFO_UPDATE_RESET'
