export const CORPORATE_LIST_REQUEST = 'CORPORATE_LIST_REQUEST'
export const CORPORATE_LIST_SUCCESS = 'CORPORATE_LIST_SUCCESS'
export const CORPORATE_LIST_FAIL = 'CORPORATE_LIST_FAIL'

export const CORPORATE_DETAILS_REQUEST = 'CORPORATE_DETAILS_REQUEST'
export const CORPORATE_DETAILS_SUCCESS = 'CORPORATE_DETAILS_SUCCESS'
export const CORPORATE_DETAILS_FAIL = 'CORPORATE_DETAILS_FAIL'

export const CORPORATE_DELETE_REQUEST = 'CORPORATE_DELETE_REQUEST'
export const CORPORATE_DELETE_SUCCESS = 'CORPORATE_DELETE_SUCCESS'
export const CORPORATE_DELETE_FAIL = 'CORPORATE_DELETE_FAIL'

export const CORPORATE_CREATE_REQUEST = 'CORPORATE_CREATE_REQUEST'
export const CORPORATE_CREATE_SUCCESS = 'CORPORATE_CREATE_SUCCESS'
export const CORPORATE_CREATE_FAIL = 'CORPORATE_CREATE_FAIL'
export const CORPORATE_CREATE_RESET = 'CORPORATE_CREATE_RESET'

export const CORPORATE_UPDATE_REQUEST = 'CORPORATE_UPDATE_REQUEST'
export const CORPORATE_UPDATE_SUCCESS = 'CORPORATE_UPDATE_SUCCESS'
export const CORPORATE_UPDATE_FAIL = 'CORPORATE_UPDATE_FAIL'
export const CORPORATE_UPDATE_RESET = 'CORPORATE_UPDATE_RESET'
