export const EQUIPMENTS_LIST_REQUEST = 'EQUIPMENTS_LIST_REQUEST'
export const EQUIPMENTS_LIST_SUCCESS = 'EQUIPMENTS_LIST_SUCCESS'
export const EQUIPMENTS_LIST_FAIL = 'EQUIPMENTS_LIST_FAIL'

export const EQUIPMENTS_DETAILS_REQUEST = 'EQUIPMENTS_DETAILS_REQUEST'
export const EQUIPMENTS_DETAILS_SUCCESS = 'EQUIPMENTS_DETAILS_SUCCESS'
export const EQUIPMENTS_DETAILS_FAIL = 'EQUIPMENTS_DETAILS_FAIL'

export const EQUIPMENTS_DELETE_REQUEST = 'EQUIPMENTS_DELETE_REQUEST'
export const EQUIPMENTS_DELETE_SUCCESS = 'EQUIPMENTS_DELETE_SUCCESS'
export const EQUIPMENTS_DELETE_FAIL = 'EQUIPMENTS_DELETE_FAIL'

export const EQUIPMENTS_CREATE_REQUEST = 'EQUIPMENTS_CREATE_REQUEST'
export const EQUIPMENTS_CREATE_SUCCESS = 'EQUIPMENTS_CREATE_SUCCESS'
export const EQUIPMENTS_CREATE_FAIL = 'EQUIPMENTS_CREATE_FAIL'
export const EQUIPMENTS_CREATE_RESET = 'EQUIPMENTS_CREATE_RESET'

export const EQUIPMENTS_UPDATE_REQUEST = 'EQUIPMENTS_UPDATE_REQUEST'
export const EQUIPMENTS_UPDATE_SUCCESS = 'EQUIPMENTS_UPDATE_SUCCESS'
export const EQUIPMENTS_UPDATE_FAIL = 'EQUIPMENTS_UPDATE_FAIL'
export const EQUIPMENTS_UPDATE_RESET = 'EQUIPMENTS_UPDATE_RESET'

export const EQUIPMENTS_CREATE_REVIEW_REQUEST = 'EQUIPMENTS_CREATE_REVIEW_REQUEST'
export const EQUIPMENTS_CREATE_REVIEW_SUCCESS = 'EQUIPMENTS_CREATE_REVIEW_SUCCESS'
export const EQUIPMENTS_CREATE_REVIEW_FAIL = 'EQUIPMENTS_CREATE_REVIEW_FAIL'
export const EQUIPMENTS_CREATE_REVIEW_RESET = 'EQUIPMENTS_CREATE_REVIEW_RESET'

export const EQUIPMENTS_TOP_REQUEST = 'EQUIPMENTS_TOP_REQUEST'
export const EQUIPMENTS_TOP_SUCCESS = 'EQUIPMENTS_TOP_SUCCESS'
export const EQUIPMENTS_TOP_FAIL = 'EQUIPMENTS_TOP_FAIL'
