export const MANAGEMENT_LIST_REQUEST = 'MANAGEMENT_LIST_REQUEST'
export const MANAGEMENT_LIST_SUCCESS = 'MANAGEMENT_LIST_SUCCESS'
export const MANAGEMENT_LIST_FAIL = 'MANAGEMENT_LIST_FAIL'

export const MANAGEMENT_DETAILS_REQUEST = 'MANAGEMENT_DETAILS_REQUEST'
export const MANAGEMENT_DETAILS_SUCCESS = 'MANAGEMENT_DETAILS_SUCCESS'
export const MANAGEMENT_DETAILS_FAIL = 'MANAGEMENT_DETAILS_FAIL'

export const MANAGEMENT_DELETE_REQUEST = 'MANAGEMENT_DELETE_REQUEST'
export const MANAGEMENT_DELETE_SUCCESS = 'MANAGEMENT_DELETE_SUCCESS'
export const MANAGEMENT_DELETE_FAIL = 'MANAGEMENT_DELETE_FAIL'

export const MANAGEMENT_CREATE_REQUEST = 'MANAGEMENT_CREATE_REQUEST'
export const MANAGEMENT_CREATE_SUCCESS = 'MANAGEMENT_CREATE_SUCCESS'
export const MANAGEMENT_CREATE_FAIL = 'MANAGEMENT_CREATE_FAIL'
export const MANAGEMENT_CREATE_RESET = 'MANAGEMENT_CREATE_RESET'

export const MANAGEMENT_UPDATE_REQUEST = 'MANAGEMENT_UPDATE_REQUEST'
export const MANAGEMENT_UPDATE_SUCCESS = 'MANAGEMENT_UPDATE_SUCCESS'
export const MANAGEMENT_UPDATE_FAIL = 'MANAGEMENT_UPDATE_FAIL'
export const MANAGEMENT_UPDATE_RESET = 'MANAGEMENT_UPDATE_RESET'
