export const OVERVIEW_LIST_REQUEST = 'OVERVIEW_LIST_REQUEST'
export const OVERVIEW_LIST_SUCCESS = 'OVERVIEW_LIST_SUCCESS'
export const OVERVIEW_LIST_FAIL = 'OVERVIEW_LIST_FAIL'

export const OVERVIEW_DETAILS_REQUEST = 'OVERVIEW_DETAILS_REQUEST'
export const OVERVIEW_DETAILS_SUCCESS = 'OVERVIEW_DETAILS_SUCCESS'
export const OVERVIEW_DETAILS_FAIL = 'OVERVIEW_DETAILS_FAIL'

export const OVERVIEW_DELETE_REQUEST = 'OVERVIEW_DELETE_REQUEST'
export const OVERVIEW_DELETE_SUCCESS = 'OVERVIEW_DELETE_SUCCESS'
export const OVERVIEW_DELETE_FAIL = 'OVERVIEW_DELETE_FAIL'

export const OVERVIEW_CREATE_REQUEST = 'OVERVIEW_CREATE_REQUEST'
export const OVERVIEW_CREATE_SUCCESS = 'OVERVIEW_CREATE_SUCCESS'
export const OVERVIEW_CREATE_FAIL = 'OVERVIEW_CREATE_FAIL'
export const OVERVIEW_CREATE_RESET = 'OVERVIEW_CREATE_RESET'

export const OVERVIEW_UPDATE_REQUEST = 'OVERVIEW_UPDATE_REQUEST'
export const OVERVIEW_UPDATE_SUCCESS = 'OVERVIEW_UPDATE_SUCCESS'
export const OVERVIEW_UPDATE_FAIL = 'OVERVIEW_UPDATE_FAIL'
export const OVERVIEW_UPDATE_RESET = 'OVERVIEW_UPDATE_RESET'