export const RUNNING_PROJECT_LIST_REQUEST = 'RUNNING_PROJECT_LIST_REQUEST'
export const RUNNING_PROJECT_LIST_SUCCESS = 'RUNNING_PROJECT_LIST_SUCCESS'
export const RUNNING_PROJECT_LIST_FAIL = 'RUNNING_PROJECT_LIST_FAIL'

export const RUNNING_PROJECT_DETAILS_REQUEST = 'RUNNING_PROJECT_DETAILS_REQUEST'
export const RUNNING_PROJECT_DETAILS_SUCCESS = 'RUNNING_PROJECT_DETAILS_SUCCESS'
export const RUNNING_PROJECT_DETAILS_FAIL = 'RUNNING_PROJECT_DETAILS_FAIL'

export const RUNNING_PROJECT_DELETE_REQUEST = 'RUNNING_PROJECT_DELETE_REQUEST'
export const RUNNING_PROJECT_DELETE_SUCCESS = 'RUNNING_PROJECT_DELETE_SUCCESS'
export const RUNNING_PROJECT_DELETE_FAIL = 'RUNNING_PROJECT_DELETE_FAIL'

export const RUNNING_PROJECT_CREATE_REQUEST = 'RUNNING_PROJECT_CREATE_REQUEST'
export const RUNNING_PROJECT_CREATE_SUCCESS = 'RUNNING_PROJECT_CREATE_SUCCESS'
export const RUNNING_PROJECT_CREATE_FAIL = 'RUNNING_PROJECT_CREATE_FAIL'
export const RUNNING_PROJECT_CREATE_RESET = 'RUNNING_PROJECT_CREATE_RESET'

export const RUNNING_PROJECT_UPDATE_REQUEST = 'RUNNING_PROJECT_UPDATE_REQUEST'
export const RUNNING_PROJECT_UPDATE_SUCCESS = 'RUNNING_PROJECT_UPDATE_SUCCESS'
export const RUNNING_PROJECT_UPDATE_FAIL = 'RUNNING_PROJECT_UPDATE_FAIL'
export const RUNNING_PROJECT_UPDATE_RESET = 'RUNNING_PROJECT_UPDATE_RESET'

export const RUNNING_PROJECT_CREATE_REVIEW_REQUEST = 'RUNNING_PROJECT_CREATE_REVIEW_REQUEST'
export const RUNNING_PROJECT_CREATE_REVIEW_SUCCESS = 'RUNNING_PROJECT_CREATE_REVIEW_SUCCESS'
export const RUNNING_PROJECT_CREATE_REVIEW_FAIL = 'RUNNING_PROJECT_CREATE_REVIEW_FAIL'
export const RUNNING_PROJECT_CREATE_REVIEW_RESET = 'RUNNING_PROJECT_CREATE_REVIEW_RESET'

export const RUNNING_PROJECT_TOP_REQUEST = 'RUNNING_PROJECT_TOP_REQUEST'
export const RUNNING_PROJECT_TOP_SUCCESS = 'RUNNING_PROJECT_TOP_SUCCESS'
export const RUNNING_PROJECT_TOP_FAIL = 'RUNNING_PROJECT_TOP_FAIL'
