export const SOCIAL_MEDIA_LIST_REQUEST = 'SOCIAL_MEDIA_LIST_REQUEST'
export const SOCIAL_MEDIA_LIST_SUCCESS = 'SOCIAL_MEDIA_LIST_SUCCESS'
export const SOCIAL_MEDIA_LIST_FAIL = 'SOCIAL_MEDIA_LIST_FAIL'

export const SOCIAL_MEDIA_DETAILS_REQUEST = 'SOCIAL_MEDIA_DETAILS_REQUEST'
export const SOCIAL_MEDIA_DETAILS_SUCCESS = 'SOCIAL_MEDIA_DETAILS_SUCCESS'
export const SOCIAL_MEDIA_DETAILS_FAIL = 'SOCIAL_MEDIA_DETAILS_FAIL'

export const SOCIAL_MEDIA_DELETE_REQUEST = 'SOCIAL_MEDIA_DELETE_REQUEST'
export const SOCIAL_MEDIA_DELETE_SUCCESS = 'SOCIAL_MEDIA_DELETE_SUCCESS'
export const SOCIAL_MEDIA_DELETE_FAIL = 'SOCIAL_MEDIA_DELETE_FAIL'

export const SOCIAL_MEDIA_CREATE_REQUEST = 'SOCIAL_MEDIA_CREATE_REQUEST'
export const SOCIAL_MEDIA_CREATE_SUCCESS = 'SOCIAL_MEDIA_CREATE_SUCCESS'
export const SOCIAL_MEDIA_CREATE_FAIL = 'SOCIAL_MEDIA_CREATE_FAIL'
export const SOCIAL_MEDIA_CREATE_RESET = 'SOCIAL_MEDIA_CREATE_RESET'

export const SOCIAL_MEDIA_UPDATE_REQUEST = 'SOCIAL_MEDIA_UPDATE_REQUEST'
export const SOCIAL_MEDIA_UPDATE_SUCCESS = 'SOCIAL_MEDIA_UPDATE_SUCCESS'
export const SOCIAL_MEDIA_UPDATE_FAIL = 'SOCIAL_MEDIA_UPDATE_FAIL'
export const SOCIAL_MEDIA_UPDATE_RESET = 'SOCIAL_MEDIA_UPDATE_RESET'
